<form method="post" action="${add_get_parameters(url, id=item_id, op_admin=op_admin, verified=verified)}">
<div class="form">
<!--    <input type="hidden" name="id" value="${item_id}">
    <input type="hidden" name="op_admin" value="${op_admin}">
    <input type="hidden" name="verified" value="${verified}">-->
    <input type="submit" value="${lang('common', 'delete_item_you_sure', 'Are you sure for delete this item?')}" /> 
</div>
</form>
