${add_js_home_local('jquery.min.js', 'admin')}

<input type="text" name="${form}_day" id="time_${form}_day" value="${d}" size="2" maxlength="2"/>
<input type="text" name="${form}_month" id="time_${form}_month" value="${m}" size="2" maxlength="2"/>
<input type="text" name="${form}_year" id="time_${form}_year" value="${y}" size="4" maxlength="4"/>
%if yes_time==True:
<input type="text" name="${form}_hour" id="time_${form}_hour" value="${h}" size="2" maxlength="2"/>
<input type="text" name="${form}_minute" id="time_${form}_minute" value="${min}" size="2" maxlength="2"/>
<input type="text" name="${form}_second" id="time_${form}_second" value="${s}" size="2" maxlength="2"/>
<input type="hidden" name="${form}" id="time_${form}" value="" />
% endif

<script language="javascript">
    $(document).submit(function  () {
    
        $("#time_${form}").val($("#time_${form}_year").val()+$("#time_${form}_month").val()+$("#time_${form}_day").val()+$("#time_${form}_hour").val()+$("#time_${form}_minute").val()+$("#time_${form}_second").val());
        
    
    });
</script>