<p>
<textarea  name="${form.name}" id="${form.name_field_id}">
    ${form.default_value}
</textarea>
</p>
<script>
tinymce.init({
    selector: '#${form.name_field_id}',
    height: 500,
    menubar: false,
    plugins: [
    'advlist autolink lists link image charmap print preview anchor',
    'searchreplace visualblocks code fullscreen',
    'insertdatetime media table contextmenu paste code'
    ],
    toolbar: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
    content_css: '//www.tinymce.com/css/codepen.min.css',
    setup: function (editor) {
        editor.on('change', function () {
            tinymce.triggerSave();
        });
    }
});
</script>
${add_js_home_local('tinymce/tinymce.min.js', 'admin')}
