<p><a href="${admin.url}">${lang('common', 'home', 'Home')}</a> &gt;&gt; 
% if id!='0':
    ${title_edit}
%else:
    ${title_edit}
%endif 
</p>
<form method="post" action="${add_get_parameters(admin.url, op_admin=2, id=id)}">
    <h2>${title_edit}</h2>
    <span class="error">${model.query_error}</span>
    ${ form|n }
    <p><input type="submit" value="${lang('common', 'send', 'Send') }"></p>
</form>